export const expensesCategories = [
  { label: "Electridad", value: "electricidad", id: 1 },
  { label: "Internet", value: "Internet", id: 2 },
  { label: "Streaming", value: "streaming", id: 3 },
  { label: "Carro", value: "carro", id: 4 },
  { label: "Telefonia", value: "Telefonia", id: 5 },
  { label: "Gasolina", value: "Gasolina", id: 6 },
  { label: "Tiendas departamentales", value: "tiendas", id: 7 },
  { label: "Otros", value: "otros", id: 8 },
  { label: "Medicos", value: "medicos", id: 9 },
  { label: "PPR", value: "ppr", id: 10 },
  { label: "Acciones", value: "acciones", id: 11 },
  { label: "YoTePresto", value: "yotepresto", id: 12 },
  { label: "Fibras", value: "fibras", id: 13 },
  { label: "Emergencias", value: "emergencias", id: 14 },
  { label: "Disponible", value: "Disponible", id: 15 },
  { label: "Transporte", value: "transporte", id: 16 },
  { label: "Seguros", value: "seguros", id: 17 },
];
